name: Fetch Electricity Data (Deprecated - Use Docker version)

on:
  # schedule:
  #   # 每天早上7点和晚上7点（北京时间）执行，使用UTC时间需要减8小时
  #   - cron: '0 23 * * *'  # 北京时间早上7点 (UTC 23点前一天)
  #   - cron: '0 11 * * *'  # 北京时间晚上7点 (UTC 11点)
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        # 基础依赖和运行时库（含 xz-utils 以支持 .tar.xz 解压）
        sudo apt-get install -y curl tar bzip2 xz-utils ca-certificates \
          libgtk-3-0 libdbus-glib-1-2 libx11-xcb1 libxtst6 libxrandr2 libxss1 libnss3 fonts-liberation libgbm1
        # Ubuntu 24.04 使用 t64 套件命名，尝试安装 t64，失败则退回旧包名
        sudo apt-get install -y libasound2t64 || sudo apt-get install -y libasound2 || true
        # 安装官方 Firefox 二进制（跟随重定向，获取真实下载地址，兼容 tar.bz2 / tar.xz）
        FIREFOX_URL=$(curl -sI "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" | awk -F': ' 'tolower($1)=="location"{print $2}' | tr -d '\r')
        curl -L -o firefox.tar "$FIREFOX_URL"
        sudo tar -xf firefox.tar -C /opt/
        sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
        /usr/bin/firefox --version
        # 下载并安装最新版本的 geckodriver（使用 jq 解析 JSON 获取下载链接，排除 .asc 签名文件）
        sudo apt-get install -y jq
        GECKO_URL=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.name | (contains("linux64.tar.gz") and (contains(".asc") | not))) | .browser_download_url')
        echo "Downloading geckodriver from: $GECKO_URL"
        curl -L -o geckodriver.tar.gz "$GECKO_URL"
        tar -xzf geckodriver.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/bin/
        geckodriver --version
        
    - name: Create data directory
      run: |
        mkdir -p data
        
    - name: Run data fetcher
      env:
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        IGNORE_USER_ID: ${{ secrets.IGNORE_USER_ID }}
        ENABLE_DATABASE_STORAGE: 'false'
        HASS_URL: 'http://localhost:8123/'
        HASS_TOKEN: 'dummy_token'
        JOB_START_TIME: '07:00'
        RETRY_WAIT_TIME_OFFSET_UNIT: '20'
        DRIVER_IMPLICITY_WAIT_TIME: '120'
        LOGIN_EXPECTED_TIME: '30'
        RETRY_TIMES_LIMIT: '3'
        DATA_RETENTION_DAYS: '7'
        RECHARGE_NOTIFY: 'false'
        BALANCE: '5.0'
        PUSHPLUS_TOKEN: ''
        PYTHON_IN_DOCKER: 'true'
        VERSION: 'github-actions'
        OUTPUT_JSON: 'true'
      run: |
        cd scripts
        python main_github.py
        
    - name: Commit and push data
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/electricity_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update electricity data $(date +'%Y-%m-%d %H:%M:%S')" && git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }})

